definitions:
  app.Meta:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  app.Response:
    properties:
      data:
        type: object
      meta:
        $ref: '#/definitions/app.Meta'
        type: object
    type: object
  body.Body:
    additionalProperties: true
    type: object
  utils.ApiListForm:
    properties:
      apiGroup:
        description: 组名
        type: string
      description:
        description: 中文描述
        type: string
      method:
        description: 请求方式
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      path:
        description: api路径
        type: string
    type: object
  utils.FormAPIGroupAdd:
    properties:
      apiGroup:
        description: 组名
        type: string
      description:
        description: 中文描述
        type: string
      method:
        description: 请求方式
        type: string
      path:
        description: api路径
        type: string
    required:
    - apiGroup
    - description
    - method
    - path
    type: object
  utils.FormAPIGroupEdit:
    properties:
      apiGroup:
        description: 组名
        type: string
      description:
        description: 中文描述
        type: string
      id:
        type: integer
      method:
        description: 请求方式
        type: string
      path:
        description: api路径
        type: string
    required:
    - apiGroup
    - description
    - id
    - method
    - path
    type: object
  utils.FormAddMenu:
    properties:
      component:
        type: string
      meta:
        additionalProperties: true
        type: object
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
      sort:
        type: integer
    required:
    - component
    - meta
    - name
    - parentId
    - path
    type: object
  utils.FormEditUser:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        description: Username *string `json:"username" form:"username"`
        type: string
      phone:
        type: string
      role:
        type: integer
      sign:
        type: string
      status:
        type: string
      uid:
        type: string
    required:
    - uid
    type: object
  utils.FormIDCard:
    properties:
      cardId:
        description: 身份证号
        type: string
      cardIdAddr:
        description: 身份证地址
        type: string
      issueOrg:
        description: 身份证发证机关
        type: string
      name:
        type: string
      nation:
        description: Sex         int    `json:"sex" form:"sex" binding:"required"`
        type: string
      validPeriod:
        description: Birthday    string `json:"birthday" from:"birthday" binding:"required"`       // 出生日期
        type: string
    required:
    - cardId
    - cardIdAddr
    - issueOrg
    - name
    - nation
    - validPeriod
    type: object
  utils.FormRoleAPIPerm:
    properties:
      groupIds:
        description: api id
        items:
          type: integer
        type: array
      uid:
        description: 角色uid
        type: string
    required:
    - groupIds
    - uid
    type: object
  utils.FormUpdateMenu:
    properties:
      component:
        type: string
      id:
        type: integer
      meta:
        $ref: '#/definitions/body.Body'
        type: object
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
      sort:
        type: integer
    required:
    - id
    type: object
  utils.FormUserList:
    properties:
      createdTime:
        description: 创建时间
        type: string
      id:
        description: ID
        type: string
      pageNum:
        type: integer
      pageSize:
        type: integer
      status:
        description: 状态
        type: string
      username:
        description: 用户名
        type: string
    type: object
  utils.LoginForm:
    properties:
      captchaId:
        type: string
      deviceId:
        type: string
      digits:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/admin/addMenu:
    post:
      parameters:
      - description: 菜单form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/utils.FormAddMenu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 添加菜单
      tags:
      - 超级管理员
  /api/v1/admin/deleteUser:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 用户UID
        in: query
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 删除用户
      tags:
      - 管理员
  /api/v1/admin/getMenu:
    get:
      consumes:
      - application/json
      description: 获取菜单
      parameters:
      - description: 菜单id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取菜单
      tags:
      - 管理员
  /api/v1/admin/getMenuList:
    get:
      consumes:
      - application/json
      description: 获取菜单
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取菜单
      tags:
      - 管理员
  /api/v1/admin/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 管理员登录
      tags:
      - 管理员
  /api/v1/admin/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 管理员登出
      tags:
      - 管理员
  /api/v1/captcha:
    get:
      consumes:
      - application/json
      parameters:
      - description: 图片格式
        in: query
        name: ext
        type: string
      - description: 语言
        in: query
        name: lang
        type: string
      - description: true：下载
        in: query
        name: isDownload
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取验证码
      tags:
      - 验证码
  /api/v1/getUserKV:
    get:
      consumes:
      - application/json
      description: 获取用户表状态信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取用户表状态信息
      tags:
      - 管理员
  /api/v1/register:
    post:
      parameters:
      - description: Phone
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Code
        in: body
        name: codes
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户注册
      tags:
      - 用户
  /api/v1/user/login:
    post:
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/utils.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户登录
      tags:
      - 用户
  /api/v1/user/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户登出
      tags:
      - 用户
  /api/v1/user/modifyLoginPwd:
    put:
      consumes:
      - application/json
      parameters:
      - description: 旧密码
        in: body
        name: oldPwd
        required: true
        schema:
          type: string
      - description: 新密码
        in: body
        name: newPwd
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 修改用户密码
      tags:
      - 用户
  /api/v1/user/modifyPayPwd:
    put:
      consumes:
      - application/json
      parameters:
      - description: 旧密码
        in: body
        name: oldPwd
        required: true
        schema:
          type: string
      - description: 新密码
        in: body
        name: newPwd
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 修改用户密码
      tags:
      - 用户
  /api/v1/user/modifyProfile:
    put:
      parameters:
      - description: 昵称
        in: body
        name: nickname
        schema:
          type: string
      - description: 手机号码
        in: body
        name: Phone
        schema:
          type: string
      - description: 签名
        in: body
        name: sign
        schema:
          type: string
      - description: 邮箱
        in: body
        name: email
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新用户信息
      tags:
      - 用户
  /api/v1/user/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取个人信息
      tags:
      - 用户
  /api/v1/user/verified:
    post:
      parameters:
      - description: 实名认证Form
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/utils.FormIDCard'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户实名认证
      tags:
      - 用户
swagger: "2.0"
